/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmTicTacToeMain.java
 *
 * Created on 07.Oca.2011, 22:44:18
 */

package org.tictactoeapp.frames;

import java.awt.Dimension;
import java.awt.Toolkit;
import org.tictactoeapp.frames.dialogs.DlgGameSettings;
import javax.swing.JOptionPane;
import org.tictactoeapp.pojomodels.GameScores;
import org.tictactoeapp.pojomodels.Koordinant;
import org.tictactoeapp.services.servicesimpl.NewGameImpl;
import org.tictactoeapp.singletonpack.ButtonInitializer;
import org.tictactoeapp.singletonpack.GameSystem;
/**
 *
 * @author ubuntu
 */
public class FrmTicTacToeMain extends javax.swing.JFrame {
    
    /** Creates new form FrmTicTacToeMain */
    public FrmTicTacToeMain() {
        initComponents();

        Dimension screenDimensions = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(screenDimensions.width / 4, screenDimensions.height / 4);

       GameSystem.getInstance().setGame(new NewGameImpl(true));
       FrmTicTacToeMain.newGameInitialize();
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlButtons = new javax.swing.JPanel();
        btnTTT1 = new javax.swing.JButton();
        btnTTT2 = new javax.swing.JButton();
        btnTTT9 = new javax.swing.JButton();
        btnTTT6 = new javax.swing.JButton();
        btnTTT5 = new javax.swing.JButton();
        btnTTT4 = new javax.swing.JButton();
        btnTTT3 = new javax.swing.JButton();
        btnTTT8 = new javax.swing.JButton();
        btnTTT7 = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnNewGame = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        lblYourScore = new javax.swing.JLabel();
        lblComputerScore = new javax.swing.JLabel();
        txtYourScore = new javax.swing.JTextField();
        txtComputerScore = new javax.swing.JTextField();
        txtDrawScore = new javax.swing.JTextField();
        lblDrawScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MadBlazer's Tic Tac Toe");

        pnlButtons.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnTTT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTTT1ActionPerformed(evt);
            }
        });

        btnTTT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTTT2ActionPerformed(evt);
            }
        });

        btnTTT9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTTT9ActionPerformed(evt);
            }
        });

        btnTTT6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTTT6ActionPerformed(evt);
            }
        });

        btnTTT5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTTT5ActionPerformed(evt);
            }
        });

        btnTTT4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTTT4ActionPerformed(evt);
            }
        });

        btnTTT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTTT3ActionPerformed(evt);
            }
        });

        btnTTT8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTTT8ActionPerformed(evt);
            }
        });

        btnTTT7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTTT7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonsLayout = new javax.swing.GroupLayout(pnlButtons);
        pnlButtons.setLayout(pnlButtonsLayout);
        pnlButtonsLayout.setHorizontalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonsLayout.createSequentialGroup()
                .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTTT7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTTT4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTTT1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlButtonsLayout.createSequentialGroup()
                        .addComponent(btnTTT8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTTT9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlButtonsLayout.createSequentialGroup()
                        .addComponent(btnTTT2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTTT3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlButtonsLayout.createSequentialGroup()
                        .addComponent(btnTTT5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTTT6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        pnlButtonsLayout.setVerticalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonsLayout.createSequentialGroup()
                .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTTT3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTTT1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTTT2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTTT4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTTT5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTTT6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTTT7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTTT8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTTT9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 18));
        lblTitle.setText("MadBlazer's Tic Tac Toe");

        btnNewGame.setText("Yeni Oyun");
        btnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewGameActionPerformed(evt);
            }
        });

        btnClose.setText("Kapat");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnAbout.setText("Hakkında");
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });

        lblYourScore.setText("Sizin Skorunuz : ");

        lblComputerScore.setText("Bilgisayar Skoru : ");

        txtYourScore.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtYourScore.setText("0");

        txtComputerScore.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtComputerScore.setText("0");

        txtDrawScore.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDrawScore.setText("0");

        lblDrawScore.setText("Beraberlik : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(lblTitle)
                .addContainerGap(151, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblYourScore)
                            .addComponent(lblComputerScore)
                            .addComponent(lblDrawScore))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtComputerScore, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtYourScore, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(txtDrawScore))))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtYourScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblYourScore))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtComputerScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblComputerScore))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDrawScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDrawScore))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(btnAbout, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(btnNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTTT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTTT1ActionPerformed
        GameSystem.getInstance().getGame().getGameCore().playerGame(0, 0);
        btnTTT1.setEnabled(false);
        btnTTT1.setText(GameSystem.getInstance().getGame().getGameSettings().getPlayerPoint());
        btnTTT1.setForeground(GameSystem.getInstance().getGame().getGameSettings().getPlayerColor());
        playerGaming();
    }//GEN-LAST:event_btnTTT1ActionPerformed

    private void btnTTT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTTT2ActionPerformed
        GameSystem.getInstance().getGame().getGameCore().playerGame(0, 1);
        btnTTT2.setEnabled(false);
        btnTTT2.setText(GameSystem.getInstance().getGame().getGameSettings().getPlayerPoint());
        btnTTT2.setForeground(GameSystem.getInstance().getGame().getGameSettings().getPlayerColor());
        playerGaming();
    }//GEN-LAST:event_btnTTT2ActionPerformed

    private void btnTTT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTTT3ActionPerformed
        GameSystem.getInstance().getGame().getGameCore().playerGame(0, 2);
        btnTTT3.setEnabled(false);
        btnTTT3.setText(GameSystem.getInstance().getGame().getGameSettings().getPlayerPoint());
        btnTTT3.setForeground(GameSystem.getInstance().getGame().getGameSettings().getPlayerColor());
        playerGaming();
    }//GEN-LAST:event_btnTTT3ActionPerformed

    private void btnTTT4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTTT4ActionPerformed
        GameSystem.getInstance().getGame().getGameCore().playerGame(1, 0);
        btnTTT4.setEnabled(false);
        btnTTT4.setText(GameSystem.getInstance().getGame().getGameSettings().getPlayerPoint());
        btnTTT4.setForeground(GameSystem.getInstance().getGame().getGameSettings().getPlayerColor());
        playerGaming();
    }//GEN-LAST:event_btnTTT4ActionPerformed

    private void btnTTT5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTTT5ActionPerformed
        GameSystem.getInstance().getGame().getGameCore().playerGame(1, 1);
        btnTTT5.setEnabled(false);
        btnTTT5.setText(GameSystem.getInstance().getGame().getGameSettings().getPlayerPoint());
        btnTTT5.setForeground(GameSystem.getInstance().getGame().getGameSettings().getPlayerColor());
        playerGaming();
    }//GEN-LAST:event_btnTTT5ActionPerformed

    private void btnTTT6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTTT6ActionPerformed
        GameSystem.getInstance().getGame().getGameCore().playerGame(1, 2);
        btnTTT6.setEnabled(false);
        btnTTT6.setText(GameSystem.getInstance().getGame().getGameSettings().getPlayerPoint());
        btnTTT6.setForeground(GameSystem.getInstance().getGame().getGameSettings().getPlayerColor());
        playerGaming();
    }//GEN-LAST:event_btnTTT6ActionPerformed

    private void btnTTT7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTTT7ActionPerformed
        GameSystem.getInstance().getGame().getGameCore().playerGame(2, 0);
        btnTTT7.setEnabled(false);
        btnTTT7.setText(GameSystem.getInstance().getGame().getGameSettings().getPlayerPoint());
        btnTTT7.setForeground(GameSystem.getInstance().getGame().getGameSettings().getPlayerColor());
        playerGaming();
    }//GEN-LAST:event_btnTTT7ActionPerformed

    private void btnTTT8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTTT8ActionPerformed
        GameSystem.getInstance().getGame().getGameCore().playerGame(2, 1);
        btnTTT8.setEnabled(false);
        btnTTT8.setText(GameSystem.getInstance().getGame().getGameSettings().getPlayerPoint());
        btnTTT8.setForeground(GameSystem.getInstance().getGame().getGameSettings().getPlayerColor());
        playerGaming();
    }//GEN-LAST:event_btnTTT8ActionPerformed

    private void btnTTT9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTTT9ActionPerformed
        GameSystem.getInstance().getGame().getGameCore().playerGame(2, 2);
        btnTTT9.setEnabled(false);
        btnTTT9.setText(GameSystem.getInstance().getGame().getGameSettings().getPlayerPoint());
        btnTTT9.setForeground(GameSystem.getInstance().getGame().getGameSettings().getPlayerColor());
        playerGaming();
    }//GEN-LAST:event_btnTTT9ActionPerformed

    private void btnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewGameActionPerformed
            DlgGameSettings gameSettingsDialog = new DlgGameSettings(this, true);
            gameSettingsDialog.setVisible(true);
    }//GEN-LAST:event_btnNewGameActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        JOptionPane.showMessageDialog(null, "MadBlazer's Tic Tac Toe v0.1 BETA\nGeliştiren : "
                + "Cem Özden (MadBlazer)\nE-Mail : madblazer22@gmail.com");
    }//GEN-LAST:event_btnAboutActionPerformed

    private void playerGaming()
    {
       boolean isGameFinished = GameSystem.getInstance().getGame().getGameCore().isGameFinished();
       
       if (!isGameFinished)
       {
          Koordinant computerSelectedKoordinant =  GameSystem.getInstance().getGame().
          getGameCore().computerGame();
          
          GameSystem.getInstance().getGame().getCoreButtonList().setButtonText(computerSelectedKoordinant.getRow(),
          computerSelectedKoordinant.getColumn(), GameSystem.getInstance().getGame().getGameSettings().getComputerPoint());

          isGameFinished = GameSystem.getInstance().getGame().getGameCore().isGameFinished();

          if (isGameFinished)
          {
            GameScores gameScore = null;
            gameScore = addScore(1);
            txtComputerScore.setText(String.valueOf(gameScore.getComputerScore()));
            JOptionPane.showMessageDialog(null, "Bilgisayar bu turu kazandı !");
            reInitializeGame();
          }
          
       }
       else
       {
           Boolean isPlayerWinner = GameSystem.getInstance().getGame().getGameCore().isPlayerWinner();
           GameScores gameScore = null;
           
           if (isPlayerWinner == null)
           {
              gameScore = addScore(2);
              txtDrawScore.setText(String.valueOf(gameScore.getDrawScore()));
              JOptionPane.showMessageDialog(null, "Tur berabere bitti !");
             
           }
           else if(isPlayerWinner)
           {
           gameScore = addScore(0);
           txtYourScore.setText(String.valueOf(gameScore.getPlayerScore()));
           JOptionPane.showMessageDialog(null, "Tebrikler bu turu siz kazandınız !");
           }
           

           else
           {
            gameScore = addScore(1);
            txtComputerScore.setText(String.valueOf(gameScore.getComputerScore()));
            JOptionPane.showMessageDialog(null, "Bilgisayar bu turu kazandı !");
           }
           reInitializeGame();
       }
    }

    private void reInitializeGame()
    {
        GameSystem.getInstance().getGame().getCoreButtonList().getButtonList().clear();
        GameSystem.getInstance().getGame().getGameCore().getGameValuesList().clear();
        GameSystem.getInstance().getGame().getGameCore().initializeCore();
        
        ButtonInitializer.getInstance().initializeButtons(true);
    }

    private GameScores addScore(int winner)
    {
        
        GameSystem.getInstance().getGame().setGameScore(winner);

        return GameSystem.getInstance().getGame().getGameScores();
    }

    public static void newGameInitialize()
    {
       /* for (JButton[] buttons : GameSystem.getInstance().getGame().getCoreButtonList().
        getButtonList())
        {
            for (JButton addedButton : buttons)
            {
                if (addedButton.getText().equals(GameSystem.getInstance().getGame().getGameSettings().getPlayerPoint()))
                addedButton.setForeground(GameSystem.getInstance().getGame().getGameSettings().getPlayerColor());

            }
        }
*/
        txtYourScore.setText(String.valueOf(GameSystem.getInstance().getGame().getGameScores().getPlayerScore()));
        txtComputerScore.setText(String.valueOf(GameSystem.getInstance().getGame().getGameScores().getComputerScore()));
        txtDrawScore.setText(String.valueOf(GameSystem.getInstance().getGame().getGameScores().getDrawScore()));
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTicTacToeMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnNewGame;
    public static javax.swing.JButton btnTTT1;
    public static javax.swing.JButton btnTTT2;
    public static javax.swing.JButton btnTTT3;
    public static javax.swing.JButton btnTTT4;
    public static javax.swing.JButton btnTTT5;
    public static javax.swing.JButton btnTTT6;
    public static javax.swing.JButton btnTTT7;
    public static javax.swing.JButton btnTTT8;
    public static javax.swing.JButton btnTTT9;
    private javax.swing.JLabel lblComputerScore;
    private javax.swing.JLabel lblDrawScore;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblYourScore;
    private javax.swing.JPanel pnlButtons;
    private static javax.swing.JTextField txtComputerScore;
    private static javax.swing.JTextField txtDrawScore;
    private static javax.swing.JTextField txtYourScore;
    // End of variables declaration//GEN-END:variables

}
